
server:
  port: 8764

spring:
  application:
    name: eureka-client-2

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8762/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/