server:
  port: 8766

spring:
  application:
    name: zuul-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

zuul:
  routes:
    api-client1:
      path: /api-client1/**
      serviceId: eureka-client
    api-feign:
      path: /api-feign/**
      serviceId: feign-client


